package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name="categorie"
    ,catalog="gestionvehiculepfe"
)
public class Categorie  implements java.io.Serializable {


     private Integer idCategorie;
     private String libelleCategorie;
     private Set<Panne> pannes = new HashSet<Panne>(0);

    public Categorie() {
    }

	
    public Categorie(String libelleCategorie) {
        this.libelleCategorie = libelleCategorie;
    }
    public Categorie(String libelleCategorie, Set<Panne> pannes) {
       this.libelleCategorie = libelleCategorie;
       this.pannes = pannes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCategorie", unique=true, nullable=false)
    public Integer getIdCategorie() {
        return this.idCategorie;
    }
    
    public void setIdCategorie(Integer idCategorie) {
        this.idCategorie = idCategorie;
    }

    
    @Column(name="libelleCategorie", nullable=false, length=30)
    public String getLibelleCategorie() {
        return this.libelleCategorie;
    }
    
    public void setLibelleCategorie(String libelleCategorie) {
        this.libelleCategorie = libelleCategorie;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorie")
    public Set<Panne> getPannes() {
        return this.pannes;
    }
    
    public void setPannes(Set<Panne> pannes) {
        this.pannes = pannes;
    }




}


