package com.pfe.model;
// Generated 29 avr. 2015 00:11:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name="transaction"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="idUtilisateur") 
)
public class Transaction  implements java.io.Serializable {


     private Integer idTransaction;
     private Date dateTransaction;
     private String libelleTransaction;
     private Utilisateur utilisateur;

    public Transaction() {
    }

    public Transaction(Date dateTransaction, String libelleTransaction, Utilisateur utilisateur) {
       this.dateTransaction = dateTransaction;
       this.libelleTransaction = libelleTransaction;
       this.utilisateur = utilisateur;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTransaction", unique=true, nullable=false)
    public Integer getIdTransaction() {
        return this.idTransaction;
    }
    
    public void setIdTransaction(Integer idTransaction) {
        this.idTransaction = idTransaction;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateTransaction", nullable=false, length=19)
    public Date getDateTransaction() {
        return this.dateTransaction;
    }
    
    public void setDateTransaction(Date dateTransaction) {
        this.dateTransaction = dateTransaction;
    }

    
    @Column(name="libelleTransaction", nullable=false, length=40)
    public String getLibelleTransaction() {
        return this.libelleTransaction;
    }
    
    public void setLibelleTransaction(String libelleTransaction) {
        this.libelleTransaction = libelleTransaction;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUtilisateur", unique=true, nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }




}


