package com.pfe.model;
// Generated 29 avr. 2015 00:11:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Alertevidange generated by hbm2java
 */
@Entity
@Table(name="alertevidange"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="idVehicule") 
)
public class Alertevidange  implements java.io.Serializable {


     private Integer idAlerteVidange;
     private String desceription;
     private double kilometrageAlert;
     private Vehicule vehicule;

    public Alertevidange() {
    }

    public Alertevidange(String desceription, double kilometrageAlert, Vehicule vehicule) {
       this.desceription = desceription;
       this.kilometrageAlert = kilometrageAlert;
       this.vehicule = vehicule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAlerteVidange", unique=true, nullable=false)
    public Integer getIdAlerteVidange() {
        return this.idAlerteVidange;
    }
    
    public void setIdAlerteVidange(Integer idAlerteVidange) {
        this.idAlerteVidange = idAlerteVidange;
    }

    
    @Column(name="desceription", nullable=false, length=65535)
    public String getDesceription() {
        return this.desceription;
    }
    
    public void setDesceription(String desceription) {
        this.desceription = desceription;
    }

    
    @Column(name="kilometrageAlert", nullable=false, precision=22, scale=0)
    public double getKilometrageAlert() {
        return this.kilometrageAlert;
    }
    
    public void setKilometrageAlert(double kilometrageAlert) {
        this.kilometrageAlert = kilometrageAlert;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVehicule", unique=true, nullable=false)
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }




}


