package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Visitetechnique generated by hbm2java
 */
@Entity
@Table(name="visitetechnique"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = {@UniqueConstraint(columnNames="idCentreVisiteTechnique"), @UniqueConstraint(columnNames="idVehicule")} 
)
public class Visitetechnique  implements java.io.Serializable {


     private Integer idVisiteTechnique;
     private int dateControle;
     private int kilometrage;
     private int ripage;
     private int opacite;
     private int eefFrScv;
     private int eefFrSt;
     private int dateProchaineVisite;
     private int idCentreVisiteTechnique;
     private int idVehicule;

    public Visitetechnique() {
    }

    public Visitetechnique(int dateControle, int kilometrage, int ripage, int opacite, int eefFrScv, int eefFrSt, int dateProchaineVisite, int idCentreVisiteTechnique, int idVehicule) {
       this.dateControle = dateControle;
       this.kilometrage = kilometrage;
       this.ripage = ripage;
       this.opacite = opacite;
       this.eefFrScv = eefFrScv;
       this.eefFrSt = eefFrSt;
       this.dateProchaineVisite = dateProchaineVisite;
       this.idCentreVisiteTechnique = idCentreVisiteTechnique;
       this.idVehicule = idVehicule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVisiteTechnique", unique=true, nullable=false)
    public Integer getIdVisiteTechnique() {
        return this.idVisiteTechnique;
    }
    
    public void setIdVisiteTechnique(Integer idVisiteTechnique) {
        this.idVisiteTechnique = idVisiteTechnique;
    }

    
    @Column(name="dateControle", nullable=false)
    public int getDateControle() {
        return this.dateControle;
    }
    
    public void setDateControle(int dateControle) {
        this.dateControle = dateControle;
    }

    
    @Column(name="kilometrage", nullable=false)
    public int getKilometrage() {
        return this.kilometrage;
    }
    
    public void setKilometrage(int kilometrage) {
        this.kilometrage = kilometrage;
    }

    
    @Column(name="ripage", nullable=false)
    public int getRipage() {
        return this.ripage;
    }
    
    public void setRipage(int ripage) {
        this.ripage = ripage;
    }

    
    @Column(name="opacite", nullable=false)
    public int getOpacite() {
        return this.opacite;
    }
    
    public void setOpacite(int opacite) {
        this.opacite = opacite;
    }

    
    @Column(name="eef_fr_scv", nullable=false)
    public int getEefFrScv() {
        return this.eefFrScv;
    }
    
    public void setEefFrScv(int eefFrScv) {
        this.eefFrScv = eefFrScv;
    }

    
    @Column(name="eef_fr_st", nullable=false)
    public int getEefFrSt() {
        return this.eefFrSt;
    }
    
    public void setEefFrSt(int eefFrSt) {
        this.eefFrSt = eefFrSt;
    }

    
    @Column(name="dateProchaineVisite", nullable=false)
    public int getDateProchaineVisite() {
        return this.dateProchaineVisite;
    }
    
    public void setDateProchaineVisite(int dateProchaineVisite) {
        this.dateProchaineVisite = dateProchaineVisite;
    }

    
    @Column(name="idCentreVisiteTechnique", unique=true, nullable=false)
    public int getIdCentreVisiteTechnique() {
        return this.idCentreVisiteTechnique;
    }
    
    public void setIdCentreVisiteTechnique(int idCentreVisiteTechnique) {
        this.idCentreVisiteTechnique = idCentreVisiteTechnique;
    }

    
    @Column(name="idVehicule", unique=true, nullable=false)
    public int getIdVehicule() {
        return this.idVehicule;
    }
    
    public void setIdVehicule(int idVehicule) {
        this.idVehicule = idVehicule;
    }




}


