package com.pfe.model;
// Generated 29 avr. 2015 00:11:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Centrevisitetechnique generated by hbm2java
 */
@Entity
@Table(name="centrevisitetechnique"
    ,catalog="gestionvehiculepfe"
)
public class Centrevisitetechnique  implements java.io.Serializable {


     private Integer idCentreVisiteTechnique;
     private String adresse;
     private String fax;
     private String nomCentre;
     private String numeroAutorisation;
     private String tel;

    public Centrevisitetechnique() {
    }

    public Centrevisitetechnique(String adresse, String fax, String nomCentre, String numeroAutorisation, String tel) {
       this.adresse = adresse;
       this.fax = fax;
       this.nomCentre = nomCentre;
       this.numeroAutorisation = numeroAutorisation;
       this.tel = tel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCentreVisiteTechnique", unique=true, nullable=false)
    public Integer getIdCentreVisiteTechnique() {
        return this.idCentreVisiteTechnique;
    }
    
    public void setIdCentreVisiteTechnique(Integer idCentreVisiteTechnique) {
        this.idCentreVisiteTechnique = idCentreVisiteTechnique;
    }

    
    @Column(name="adresse", nullable=false, length=30)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="fax", nullable=false, length=15)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="nomCentre", nullable=false, length=40)
    public String getNomCentre() {
        return this.nomCentre;
    }
    
    public void setNomCentre(String nomCentre) {
        this.nomCentre = nomCentre;
    }

    
    @Column(name="numeroAutorisation", nullable=false, length=30)
    public String getNumeroAutorisation() {
        return this.numeroAutorisation;
    }
    
    public void setNumeroAutorisation(String numeroAutorisation) {
        this.numeroAutorisation = numeroAutorisation;
    }

    
    @Column(name="tel", nullable=false, length=15)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }




}


