package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typecarburant generated by hbm2java
 */
@Entity
@Table(name="typecarburant"
    ,catalog="gestionvehiculepfe"
)
public class Typecarburant  implements java.io.Serializable {


     private Integer idTypeCarburant;
     private String libelleTypeCarburant;
     private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

    public Typecarburant() {
    }

	
    public Typecarburant(String libelleTypeCarburant) {
        this.libelleTypeCarburant = libelleTypeCarburant;
    }
    public Typecarburant(String libelleTypeCarburant, Set<Vehicule> vehicules) {
       this.libelleTypeCarburant = libelleTypeCarburant;
       this.vehicules = vehicules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTypeCarburant", unique=true, nullable=false)
    public Integer getIdTypeCarburant() {
        return this.idTypeCarburant;
    }
    
    public void setIdTypeCarburant(Integer idTypeCarburant) {
        this.idTypeCarburant = idTypeCarburant;
    }

    
    @Column(name="libelleTypeCarburant", nullable=false, length=20)
    public String getLibelleTypeCarburant() {
        return this.libelleTypeCarburant;
    }
    
    public void setLibelleTypeCarburant(String libelleTypeCarburant) {
        this.libelleTypeCarburant = libelleTypeCarburant;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typecarburant")
    public Set<Vehicule> getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }




}


