package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proprietairevehicule generated by hbm2java
 */
@Entity
@Table(name="proprietairevehicule"
    ,catalog="gestionvehiculepfe"
)
public class Proprietairevehicule  implements java.io.Serializable {


     private Integer idProprietaire;
     private String nom;
     private String prenom;
     private String adresse;
     private String cinRc;
     private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

    public Proprietairevehicule() {
    }

	
    public Proprietairevehicule(String nom, String prenom, String adresse, String cinRc) {
        this.nom = nom;
        this.prenom = prenom;
        this.adresse = adresse;
        this.cinRc = cinRc;
    }
    public Proprietairevehicule(String nom, String prenom, String adresse, String cinRc, Set<Vehicule> vehicules) {
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.cinRc = cinRc;
       this.vehicules = vehicules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProprietaire", unique=true, nullable=false)
    public Integer getIdProprietaire() {
        return this.idProprietaire;
    }
    
    public void setIdProprietaire(Integer idProprietaire) {
        this.idProprietaire = idProprietaire;
    }

    
    @Column(name="nom", nullable=false, length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=20)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="adresse", nullable=false, length=40)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="cin _RC", nullable=false, length=30)
    public String getCinRc() {
        return this.cinRc;
    }
    
    public void setCinRc(String cinRc) {
        this.cinRc = cinRc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proprietairevehicule")
    public Set<Vehicule> getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }




}


