package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Vignette generated by hbm2java
 */
@Entity
@Table(name="vignette"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="idVehicule") 
)
public class Vignette  implements java.io.Serializable {


     private Integer idVignette;
     private Vehicule vehicule;
     private Date dateDebut;
     private Date dateFin;
     private String genre;

    public Vignette() {
    }

    public Vignette(Vehicule vehicule, Date dateDebut, Date dateFin, String genre) {
       this.vehicule = vehicule;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.genre = genre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVignette", unique=true, nullable=false)
    public Integer getIdVignette() {
        return this.idVignette;
    }
    
    public void setIdVignette(Integer idVignette) {
        this.idVignette = idVignette;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVehicule", unique=true, nullable=false)
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateDebut", nullable=false, length=10)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateFin", nullable=false, length=10)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="genre", nullable=false, length=30)
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }




}


