package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entrepriseassurance generated by hbm2java
 */
@Entity
@Table(name="entrepriseassurance"
    ,catalog="gestionvehiculepfe"
)
public class Entrepriseassurance  implements java.io.Serializable {


     private Integer idEntrepriseAssurance;
     private String numeroPolice;
     private String nom;
     private String adresse;
     private String intermediaire;
     private Set<Assurance> assurances = new HashSet<Assurance>(0);

    public Entrepriseassurance() {
    }

	
    public Entrepriseassurance(String numeroPolice, String nom, String adresse, String intermediaire) {
        this.numeroPolice = numeroPolice;
        this.nom = nom;
        this.adresse = adresse;
        this.intermediaire = intermediaire;
    }
    public Entrepriseassurance(String numeroPolice, String nom, String adresse, String intermediaire, Set<Assurance> assurances) {
       this.numeroPolice = numeroPolice;
       this.nom = nom;
       this.adresse = adresse;
       this.intermediaire = intermediaire;
       this.assurances = assurances;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEntrepriseAssurance", unique=true, nullable=false)
    public Integer getIdEntrepriseAssurance() {
        return this.idEntrepriseAssurance;
    }
    
    public void setIdEntrepriseAssurance(Integer idEntrepriseAssurance) {
        this.idEntrepriseAssurance = idEntrepriseAssurance;
    }

    
    @Column(name="numeroPolice", nullable=false, length=30)
    public String getNumeroPolice() {
        return this.numeroPolice;
    }
    
    public void setNumeroPolice(String numeroPolice) {
        this.numeroPolice = numeroPolice;
    }

    
    @Column(name="nom", nullable=false, length=30)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="adresse", nullable=false, length=30)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="intermediaire", nullable=false, length=30)
    public String getIntermediaire() {
        return this.intermediaire;
    }
    
    public void setIntermediaire(String intermediaire) {
        this.intermediaire = intermediaire;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="entrepriseassurance")
    public Set<Assurance> getAssurances() {
        return this.assurances;
    }
    
    public void setAssurances(Set<Assurance> assurances) {
        this.assurances = assurances;
    }




}


