package com.pfe.model;
// Generated 29 avr. 2015 00:11:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pneu generated by hbm2java
 */
@Entity
@Table(name="pneu"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="idVehicule") 
)
public class Pneu  implements java.io.Serializable {


     private Integer idPneu;
     private Date dateDemontage;
     private Date dateMontage;
     private double kilometrage;
     private String marque;
     private String numeroSerie;
     private String observation;
     private String referencePneu;
     private Vehicule vehicule;

    public Pneu() {
    }

    public Pneu(Date dateDemontage, Date dateMontage, double kilometrage, String marque, String numeroSerie, String observation, String referencePneu, Vehicule vehicule) {
       this.dateDemontage = dateDemontage;
       this.dateMontage = dateMontage;
       this.kilometrage = kilometrage;
       this.marque = marque;
       this.numeroSerie = numeroSerie;
       this.observation = observation;
       this.referencePneu = referencePneu;
       this.vehicule = vehicule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPneu", unique=true, nullable=false)
    public Integer getIdPneu() {
        return this.idPneu;
    }
    
    public void setIdPneu(Integer idPneu) {
        this.idPneu = idPneu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateDemontage", nullable=false, length=10)
    public Date getDateDemontage() {
        return this.dateDemontage;
    }
    
    public void setDateDemontage(Date dateDemontage) {
        this.dateDemontage = dateDemontage;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateMontage", nullable=false, length=10)
    public Date getDateMontage() {
        return this.dateMontage;
    }
    
    public void setDateMontage(Date dateMontage) {
        this.dateMontage = dateMontage;
    }

    
    @Column(name="kilometrage", nullable=false, precision=22, scale=0)
    public double getKilometrage() {
        return this.kilometrage;
    }
    
    public void setKilometrage(double kilometrage) {
        this.kilometrage = kilometrage;
    }

    
    @Column(name="marque", nullable=false, length=30)
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }

    
    @Column(name="numeroSerie", nullable=false, length=30)
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }

    
    @Column(name="observation", nullable=false, length=40)
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    
    @Column(name="referencePneu", nullable=false, length=30)
    public String getReferencePneu() {
        return this.referencePneu;
    }
    
    public void setReferencePneu(String referencePneu) {
        this.referencePneu = referencePneu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVehicule", unique=true, nullable=false)
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }




}


