package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typevehicule generated by hbm2java
 */
@Entity
@Table(name="typevehicule"
    ,catalog="gestionvehiculepfe"
)
public class Typevehicule  implements java.io.Serializable {


     private Integer idTypeVehicule;
     private String libelleTypeVehicule;
     private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

    public Typevehicule() {
    }

	
    public Typevehicule(String libelleTypeVehicule) {
        this.libelleTypeVehicule = libelleTypeVehicule;
    }
    public Typevehicule(String libelleTypeVehicule, Set<Vehicule> vehicules) {
       this.libelleTypeVehicule = libelleTypeVehicule;
       this.vehicules = vehicules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTypeVehicule", unique=true, nullable=false)
    public Integer getIdTypeVehicule() {
        return this.idTypeVehicule;
    }
    
    public void setIdTypeVehicule(Integer idTypeVehicule) {
        this.idTypeVehicule = idTypeVehicule;
    }

    
    @Column(name="libelleTypeVehicule", nullable=false, length=40)
    public String getLibelleTypeVehicule() {
        return this.libelleTypeVehicule;
    }
    
    public void setLibelleTypeVehicule(String libelleTypeVehicule) {
        this.libelleTypeVehicule = libelleTypeVehicule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typevehicule")
    public Set<Vehicule> getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }




}


