package com.pfe.model;
// Generated 1 mai 2015 23:05:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Reparation generated by hbm2java
 */
@Entity
@Table(name="reparation"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="idPanne") 
)
public class Reparation  implements java.io.Serializable {


     private Integer idReparation;
     private Panne panne=new Panne();
     private Date dateReparation;

    public Reparation() {
    }

    public Reparation(Panne panne, Date dateReparation) {
       this.panne = panne;
       this.dateReparation = dateReparation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idReparation", unique=true, nullable=false)
    public Integer getIdReparation() {
        return this.idReparation;
    }
    
    public void setIdReparation(Integer idReparation) {
        this.idReparation = idReparation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPanne", unique=true, nullable=false)
    public Panne getPanne() {
        return this.panne;
    }
    
    public void setPanne(Panne panne) {
        this.panne = panne;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateReparation", nullable=false, length=10)
    public Date getDateReparation() {
        return this.dateReparation;
    }
    
    public void setDateReparation(Date dateReparation) {
        this.dateReparation = dateReparation;
    }




}


