package com.pfe.model;
// Generated 1 mai 2015 23:05:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = {@UniqueConstraint(columnNames="idUtilisateur"), @UniqueConstraint(columnNames="idVehicule")} 
)
public class Reservation  implements java.io.Serializable {


     private Integer idReservation;
     private Vehicule vehicule=new Vehicule();
     private Date dateDebut;
     private Date dateFin;
     private boolean etat;
     private int idUtilisateur;

    public Reservation() {
    }

    public Reservation(Vehicule vehicule, Date dateDebut, Date dateFin, boolean etat, int idUtilisateur) {
       this.vehicule = vehicule;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.etat = etat;
       this.idUtilisateur = idUtilisateur;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idReservation", unique=true, nullable=false)
    public Integer getIdReservation() {
        return this.idReservation;
    }
    
    public void setIdReservation(Integer idReservation) {
        this.idReservation = idReservation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVehicule", unique=true, nullable=false)
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateDebut", nullable=false, length=10)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateFin", nullable=false, length=10)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="etat", nullable=false)
    public boolean isEtat() {
        return this.etat;
    }
    
    public void setEtat(boolean etat) {
        this.etat = etat;
    }

    
    @Column(name="idUtilisateur", unique=true, nullable=false)
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }




}


