package com.pfe.model;
// Generated 1 mai 2015 23:05:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name="service"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="libelleService") 
)
public class Service  implements java.io.Serializable {


     private Integer idService;
     private String libelleService;
     private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

    public Service() {
    }

	
    public Service(String libelleService) {
        this.libelleService = libelleService;
    }
    public Service(String libelleService, Set<Utilisateur> utilisateurs) {
       this.libelleService = libelleService;
       this.utilisateurs = utilisateurs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idService", unique=true, nullable=false)
    public Integer getIdService() {
        return this.idService;
    }
    
    public void setIdService(Integer idService) {
        this.idService = idService;
    }

    
    @Column(name="libelleService", unique=true, nullable=false, length=30)
    public String getLibelleService() {
        return this.libelleService;
    }
    
    public void setLibelleService(String libelleService) {
        this.libelleService = libelleService;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="service")
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }




}


