package com.pfe.model;
// Generated 29 avr. 2015 00:11:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Alerteasurance generated by hbm2java
 */
@Entity
@Table(name="alerteasurance"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="idVehicule") 
)
public class Alerteasurance  implements java.io.Serializable {


     private Integer idAlerteAssurance;
     private Date dateAlert;
     private String desceription;
     private Vehicule vehicule;

    public Alerteasurance() {
    }

    public Alerteasurance(Date dateAlert, String desceription, Vehicule vehicule) {
       this.dateAlert = dateAlert;
       this.desceription = desceription;
       this.vehicule = vehicule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAlerteAssurance", unique=true, nullable=false)
    public Integer getIdAlerteAssurance() {
        return this.idAlerteAssurance;
    }
    
    public void setIdAlerteAssurance(Integer idAlerteAssurance) {
        this.idAlerteAssurance = idAlerteAssurance;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateAlert", nullable=false, length=10)
    public Date getDateAlert() {
        return this.dateAlert;
    }
    
    public void setDateAlert(Date dateAlert) {
        this.dateAlert = dateAlert;
    }

    
    @Column(name="desceription", nullable=false, length=65535)
    public String getDesceription() {
        return this.desceription;
    }
    
    public void setDesceription(String desceription) {
        this.desceription = desceription;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVehicule", unique=true, nullable=false)
    public Vehicule getVehicule() {
        return this.vehicule;
    }
    
    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }




}


