package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Reparation generated by hbm2java
 */
@Entity
@Table(name="reparation"
    ,catalog="gestionvehiculepfe"
    , uniqueConstraints = @UniqueConstraint(columnNames="idPanne") 
)
public class Reparation  implements java.io.Serializable {


     private Integer idReparation;
     private Date dateReparation;
     private int idPanne;

    public Reparation() {
    }

    public Reparation(Date dateReparation, int idPanne) {
       this.dateReparation = dateReparation;
       this.idPanne = idPanne;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idReparation", unique=true, nullable=false)
    public Integer getIdReparation() {
        return this.idReparation;
    }
    
    public void setIdReparation(Integer idReparation) {
        this.idReparation = idReparation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateReparation", nullable=false, length=10)
    public Date getDateReparation() {
        return this.dateReparation;
    }
    
    public void setDateReparation(Date dateReparation) {
        this.dateReparation = dateReparation;
    }

    
    @Column(name="idPanne", unique=true, nullable=false)
    public int getIdPanne() {
        return this.idPanne;
    }
    
    public void setIdPanne(int idPanne) {
        this.idPanne = idPanne;
    }




}


