package com.pfe.model;
// Generated 19 avr. 2015 15:18:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marque generated by hbm2java
 */
@Entity
@Table(name="marque"
    ,catalog="gestionvehiculepfe"
)
public class Marque  implements java.io.Serializable {


     private Integer idMarque;
     private String libelleMarque;
     private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

    public Marque() {
    }

	
    public Marque(String libelleMarque) {
        this.libelleMarque = libelleMarque;
    }
    public Marque(String libelleMarque, Set<Vehicule> vehicules) {
       this.libelleMarque = libelleMarque;
       this.vehicules = vehicules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMarque", unique=true, nullable=false)
    public Integer getIdMarque() {
        return this.idMarque;
    }
    
    public void setIdMarque(Integer idMarque) {
        this.idMarque = idMarque;
    }

    
    @Column(name="libelleMarque", nullable=false, length=30)
    public String getLibelleMarque() {
        return this.libelleMarque;
    }
    
    public void setLibelleMarque(String libelleMarque) {
        this.libelleMarque = libelleMarque;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="marque")
    public Set<Vehicule> getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }




}


